Repository nneaning/meaning_Android, pull requests merged in 2021-01, with the labels that each got.

#3 [feat] Home 화면 뼈대 작성
  .idea/gradle.xml
  app/build.gradle
  app/src/main/java/meaning/morning/GroupFragment.kt
  app/src/main/java/meaning/morning/HomeFragment.kt
  app/src/main/java/meaning/morning/MainActivity.kt
  app/src/main/res/drawable-hdpi/logo_img.png
  app/src/main/res/drawable-hdpi/myfeed_profile.png
  app/src/main/res/drawable-hdpi/mypage_ic.png
  app/src/main/res/drawable-hdpi/nav_item_camera_icn.png
  app/src/main/res/drawable-mdpi/logo_img.png
  app/src/main/res/drawable-mdpi/myfeed_profile.png
  app/src/main/res/drawable-mdpi/mypage_ic.png
  app/src/main/res/drawable-mdpi/nav_item_camera_icn.png
  app/src/main/res/drawable-xhdpi/logo_img.png
  app/src/main/res/drawable-xhdpi/myfeed_profile.png
  app/src/main/res/drawable-xhdpi/mypage_ic.png
  app/src/main/res/drawable-xhdpi/nav_item_camera_icn.png
  app/src/main/res/drawable-xxhdpi/logo_img.png
  app/src/main/res/drawable-xxhdpi/myfeed_profile.png
  app/src/main/res/drawable-xxhdpi/mypage_ic.png
  app/src/main/res/drawable-xxhdpi/nav_item_camera_icn.png
  app/src/main/res/drawable-xxxhdpi/logo_img.png
  app/src/main/res/drawable-xxxhdpi/myfeed_profile.png
  app/src/main/res/drawable-xxxhdpi/mypage_ic.png
  app/src/main/res/drawable-xxxhdpi/nav_item_camera_icn.png
  app/src/main/res/drawable/background_transparent.xml
  app/src/main/res/drawable/bottom_empty.xml
  app/src/main/res/drawable/ic_main_groups.xml
  app/src/main/res/drawable/ic_main_home.xml
  app/src/main/res/drawable/main_date_button.xml
  app/src/main/res/group.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_group.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/menu/main_bottom_menu.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 형준👨‍👧, 🎴Andromeaning

#10 [feat] 그룹 메인 inflate
  app/src/main/AndroidManifest.xml
  app/src/main/java/meaning/morning/BindingAdapter.kt
  app/src/main/java/meaning/morning/GroupFragment.kt
  app/src/main/java/meaning/morning/data/GroupData.kt
  app/src/main/java/meaning/morning/data/RecommendGroupData.kt
  app/src/main/java/meaning/morning/presentation/GroupFragment.kt
  app/src/main/java/meaning/morning/presentation/HomeFragment.kt
  app/src/main/java/meaning/morning/presentation/MainActivity.kt
  app/src/main/java/meaning/morning/presentation/adapter/GroupAdapter.kt
  app/src/main/java/meaning/morning/presentation/adapter/RecommendGroupAdapter.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_group.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_group_list.xml
  app/src/main/res/layout/item_group_recommend.xml
Labels: P 1️⃣, 효송🎅, 🎴Andromeaning

#13 [feat] 마이 피드 메인 페이지 inflate
  .idea/gradle.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/meaning/morning/Presentation/Adpater/MyFeedPictureAdapter.kt
  app/src/main/java/meaning/morning/Presentation/MyFeedMainActivity.kt
  app/src/main/java/meaning/morning/Presentation/MyFeedPictureData.kt
  app/src/main/java/meaning/morning/Presentation/MyFeedPictureViewHolder.kt
  app/src/main/java/meaning/morning/Presentation/adapter/MyFeedPictureAdapter.kt
  app/src/main/res/drawable/myfeed_whattime_box.xml
  app/src/main/res/layout/activity_my_feed_main.xml
  app/src/main/res/layout/item_list.xml
Labels: P 1️⃣, 형준👨‍👧, 🎴Andromeaning

#22 Inflate my feed main
  app/src/main/java/meaning/morning/Presentation/MyFeedMainActivity.kt
  app/src/main/java/meaning/morning/Presentation/adapter/MyFeedPictureAdapter.kt
  app/src/main/res/layout/activity_my_feed_main.xml
Labels: P 2️⃣, 형준👨‍👧, 🎴Andromeaning

#23 [feat] 그룹 생성 뷰 이벤트 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/meaning/morning/presentation/AddGroupActivity.kt
  app/src/main/java/meaning/morning/presentation/CompleteGroupActivity.kt
  app/src/main/java/meaning/morning/presentation/GroupFragment.kt
  app/src/main/res/drawable-hdpi/meaning_bg_3_img.png
  app/src/main/res/drawable-mdpi/meaning_bg_3_img.png
  app/src/main/res/drawable-xhdpi/meaning_bg_3_img.png
  app/src/main/res/drawable-xxhdpi/meaning_bg_3_img.png
  app/src/main/res/drawable-xxxhdpi/meaning_bg_3_img.png
  app/src/main/res/drawable/group_list_numberofpeople_background.xml
  app/src/main/res/layout/activity_add_group.xml
  app/src/main/res/layout/activity_complete_group.xml
  app/src/main/res/layout/fragment_group.xml
  app/src/main/res/layout/item_group_list.xml
  app/src/main/res/layout/item_group_recommend.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: P 1️⃣, 효송🎅, 🎴Andromeaning

#32 [feat] inflate 그룹 설정 레이아웃
  app/src/main/java/meaning/morning/data/GroupMemnerData.kt
  app/src/main/java/meaning/morning/presentation/GroupSettingActivity.kt
  app/src/main/java/meaning/morning/presentation/adapter/GroupSettingAdapter.kt
  app/src/main/res/layout/item_group_member.xml
Labels: P 2️⃣, 효송🎅, 🎴Andromeaning

#43 [feat] 서버 연결로직 작성
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/copyright/jinsu4755.xml
  app/build.gradle
  app/src/main/java/meaning/morning/network/MeaningService.kt
  app/src/main/java/meaning/morning/network/RetofitProvider.kt
  app/src/main/java/meaning/morning/network/response/BaseResponse.kt
  gradle.properties
Labels: P 0️⃣, 진수🦂, 🎴Andromeaning

#42 [feat] 그룹 블랭크 레이아웃 intent 연결
  app/src/main/AndroidManifest.xml
  app/src/main/java/meaning/morning/GroupBlankActivity.kt
  app/src/main/java/meaning/morning/presentation/AddGroupActivity.kt
  app/src/main/java/meaning/morning/presentation/CompleteGroupActivity.kt
  app/src/main/java/meaning/morning/presentation/GroupBlankActivity.kt
  app/src/main/java/meaning/morning/utils/TextWatcher.kt
  app/src/main/res/layout/activity_complete_group.xml
  app/src/main/res/layout/activity_group_blank.xml
  app/src/main/res/layout/activity_group_setting.xml
Labels: P 2️⃣, 효송🎅, 🎴Andromeaning

#41 [Inflate] 마이피드 main/sns 뷰 , 그룹피드 개인피드/sns 뷰
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/meaning/morning/Presentation/GroupFeedActivity.kt
  app/src/main/java/meaning/morning/Presentation/GroupFeedSnsActivity.kt
  app/src/main/java/meaning/morning/Presentation/MyFeedMainActivity.kt
  app/src/main/java/meaning/morning/Presentation/MyFeedPictureData.kt
  app/src/main/java/meaning/morning/Presentation/MyFeedSnsActivity.kt
  app/src/main/java/meaning/morning/Presentation/PictureRecyclerviewFragment.kt
  app/src/main/java/meaning/morning/Presentation/SnsRecyclerviewFragment.kt
  app/src/main/java/meaning/morning/Presentation/adapter/MyFeedPictureAdapter.kt
  app/src/main/java/meaning/morning/Presentation/adapter/SnsFeedAdapter.kt
  app/src/main/java/meaning/morning/Presentation/data/MyFeedPictureData.kt
  app/src/main/java/meaning/morning/Presentation/data/SnsFeedData.kt
  app/src/main/java/meaning/morning/utils/BindFeedPictureEvent.kt
  app/src/main/java/meaning/morning/utils/SnsFeedItemDecoration.kt
  app/src/main/res/drawable/myfeed_whattime_box.xml
  app/src/main/res/layout/activity_group_feed.xml
  app/src/main/res/layout/activity_group_feed_sns.xml
  app/src/main/res/layout/activity_my_feed_main.xml
  app/src/main/res/layout/activity_my_feed_sns.xml
  app/src/main/res/layout/feed_item_list.xml
  app/src/main/res/layout/fragment_picture_recyclerview.xml
  app/src/main/res/layout/fragment_sns_recyclerview.xml
  app/src/main/res/layout/sns_item_list.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: P 2️⃣, 형준👨‍👧, 🎴Andromeaning

#50 Feature/splash
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/assets/mn_splash5.json
  app/src/main/java/meaning/morning/Presentation/group/GroupFragment.kt
  app/src/main/java/meaning/morning/Presentation/home/HomeFragment.kt
  app/src/main/java/meaning/morning/SplashActivity.kt
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_group_recommend.xml
Labels: 효송🎅, 🎴Andromeaning

#53 [inflate] 미션카드2. 오늘 하루 다짐 서버 연결
  app/src/main/AndroidManifest.xml
  app/src/main/java/meaning/morning/MeaningStorage.kt
  app/src/main/java/meaning/morning/Presentation/home/card/CardPromiseActivity.kt
  app/src/main/java/meaning/morning/network/MeaningService.kt
  app/src/main/java/meaning/morning/network/response/CardTodayPromise.kt
  app/src/main/java/meaning/morning/utils/HomeCardItemDecoreation.kt
  app/src/main/java/meaning/morning/utils/customEnqueue.kt
  app/src/main/res/drawable/card_detail_button.xml
  app/src/main/res/drawable/card_promise_text.xml
  app/src/main/res/layout/activity_card_promise.xml
  app/src/main/res/layout/activity_card_write_diary.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/themes.xml
Labels: P 2️⃣, 형준👨‍👧, 🎴Andromeaning

#54 [remote] 캘린더 서버 연결
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/meaning/morning/MeaningStorage.kt
  app/src/main/java/meaning/morning/Presentation/adapter/home/CalendarAdapter.kt
  app/src/main/java/meaning/morning/Presentation/home/HomeFragment.kt
  app/src/main/java/meaning/morning/network/MeaningService.kt
  app/src/main/java/meaning/morning/network/RetofitProvider.kt
  app/src/main/java/meaning/morning/network/response/CalendarResponse.kt
  app/src/main/java/meaning/morning/utils/CalendarView.kt
  app/src/main/java/meaning/morning/utils/meaningEnqueue.kt
  app/src/main/res/drawable-hdpi/back_ic.png
  app/src/main/res/drawable-hdpi/back_ic_white.png
  app/src/main/res/drawable-mdpi/back_ic.png
  app/src/main/res/drawable-mdpi/back_ic_white.png
  app/src/main/res/drawable-xhdpi/back_ic.png
  app/src/main/res/drawable-xhdpi/back_ic_white.png
  app/src/main/res/drawable-xxhdpi/back_ic.png
  app/src/main/res/drawable-xxhdpi/back_ic_white.png
  app/src/main/res/drawable-xxxhdpi/back_ic.png
  app/src/main/res/drawable-xxxhdpi/back_ic_white.png
  app/src/main/res/layout/fragment_group.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_calendar_date.xml
Labels: 효송🎅, 🎴Andromeaning

#55 [inflate] 미션카드 3,4 (회고 일기, 독서 감상평) 서버 연결
  app/src/main/java/meaning/morning/Presentation/home/card/CardPromiseActivity.kt
  app/src/main/java/meaning/morning/Presentation/home/card/CardReadingActivity.kt
  app/src/main/java/meaning/morning/Presentation/home/card/CardWriteDiaryActivity.kt
  app/src/main/java/meaning/morning/network/MeaningService.kt
  app/src/main/java/meaning/morning/network/request/CardBookReadingRequest.kt
  app/src/main/java/meaning/morning/network/request/CardDailyDiaryRequest.kt
  app/src/main/java/meaning/morning/network/response/CardBookReadingResponse.kt
  app/src/main/java/meaning/morning/network/response/CardDailyDiaryResponse.kt
  app/src/main/java/meaning/morning/utils/customEnqueue.kt
  app/src/main/res/layout/activity_card_promise.xml
  app/src/main/res/layout/activity_card_reading.xml
  app/src/main/res/layout/activity_card_time_stamp.xml
  app/src/main/res/layout/activity_card_write_diary.xml
  app/src/main/res/layout/fragment_home.xml
Labels: P 2️⃣, 형준👨‍👧, 🎴Andromeaning

#56 [remote] 그룹 리스트 서버 연결
  app/src/main/java/meaning/morning/BindingAdapter.kt
  app/src/main/java/meaning/morning/Presentation/adapter/group/GroupAdapter.kt
  app/src/main/java/meaning/morning/Presentation/adapter/group/RecommendGroupAdapter.kt
  app/src/main/java/meaning/morning/Presentation/group/AddGroupActivity.kt
  app/src/main/java/meaning/morning/Presentation/group/GroupFragment.kt
  app/src/main/java/meaning/morning/Presentation/group/feed/GroupSettingActivity.kt
  app/src/main/java/meaning/morning/Presentation/home/HomeFragment.kt
  app/src/main/java/meaning/morning/data/GroupData.kt
  app/src/main/java/meaning/morning/data/RecommendGroupData.kt
  app/src/main/java/meaning/morning/network/MeaningService.kt
  app/src/main/java/meaning/morning/network/response/GroupListResponse.kt
  app/src/main/java/meaning/morning/utils/ShowToast.kt
  app/src/main/res/layout/activity_group_setting.xml
  app/src/main/res/layout/item_group_recommend.xml
Labels: 효송🎅, 🎴Andromeaning

#58 [remote] 가입 그룹 조회 서버 연결
  app/src/main/java/meaning/morning/network/MeaningService.kt
  app/src/main/java/meaning/morning/network/response/MyGroupResponse.kt
  app/src/main/java/meaning/morning/presentation/group/GroupFragment.kt
  app/src/main/res/layout/fragment_group.xml
Labels: 효송🎅, 🎴Andromeaning

#59 [fix] 홈 바텀 내비게이션 클릭
  app/src/main/java/meaning/morning/presentation/home/HomeFragment.kt
  app/src/main/java/meaning/morning/presentation/home/MainActivity.kt
Labels: P 2️⃣, 형준👨‍👧, 🎴Andromeaning

#60 [fix] HomeFragment 오류 수정
  app/src/main/java/meaning/morning/presentation/home/HomeFragment.kt
Labels: P 2️⃣, 형준👨‍👧, 🎴Andromeaning

#62 [fix] 마이 피드 메인 페이지 오류 수정
  app/src/main/java/meaning/morning/data/MyFeedMainListData.kt
  app/src/main/java/meaning/morning/presentation/home/card/CardReadingActivity.kt
  app/src/main/java/meaning/morning/presentation/home/card/CardWriteDiaryActivity.kt
  app/src/main/java/meaning/morning/presentation/home/feed/MyFeedSnsActivity.kt
  app/src/main/java/meaning/morning/utils/SnsFeedItemDecoration.kt
Labels: P 2️⃣, 형준👨‍👧, 🎴Andromeaning

#64 [feat] 그룹 생성 서버 연결
  app/src/main/java/meaning/morning/BindingDialog.kt
  app/src/main/java/meaning/morning/MeaningStorage.kt
  app/src/main/java/meaning/morning/data/GroupData.kt
  app/src/main/java/meaning/morning/data/GroupMemberData.kt
  app/src/main/java/meaning/morning/data/RecommendGroupData.kt
  app/src/main/java/meaning/morning/network/MeaningService.kt
  app/src/main/java/meaning/morning/network/request/GroupAddRequest.kt
  app/src/main/java/meaning/morning/network/request/GroupJoinApproveRequest.kt
  app/src/main/java/meaning/morning/network/response/GroupAddResponse.kt
  app/src/main/java/meaning/morning/network/response/GroupDetailResponse.kt
  app/src/main/java/meaning/morning/network/response/GroupJoinApproveResponse.kt
  app/src/main/java/meaning/morning/network/response/GroupSettingResponse.kt
  app/src/main/java/meaning/morning/presentation/adapter/group/GroupAdapter.kt
  app/src/main/java/meaning/morning/presentation/adapter/group/GroupSettingAdapter.kt
  app/src/main/java/meaning/morning/presentation/adapter/group/RecommendGroupAdapter.kt
  app/src/main/java/meaning/morning/presentation/group/AddGroupActivity.kt
  app/src/main/java/meaning/morning/presentation/group/GroupFragment.kt
  app/src/main/java/meaning/morning/presentation/group/feed/GroupSettingActivity.kt
  app/src/main/java/meaning/morning/presentation/home/HomeFragment.kt
  app/src/main/java/meaning/morning/utils/meaningEnqueue.kt
  app/src/main/res/layout/activity_add_group.xml
  app/src/main/res/layout/dialog_group_detail.xml
  app/src/main/res/layout/dialog_group_recycler.xml
  app/src/main/res/layout/fragment_group.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_group_member.xml
Labels: 효송🎅, 🎴Andromeaning

#66 마이 피드 메인, sns 페이지 서버 연결
  app/src/main/java/meaning/morning/data/MyFeedMainListData.kt
  app/src/main/java/meaning/morning/data/SnsFeedData.kt
  app/src/main/java/meaning/morning/presentation/adapter/feed/SnsFeedAdapter.kt
  app/src/main/java/meaning/morning/presentation/group/feed/GroupFeedSnsActivity.kt
  app/src/main/java/meaning/morning/presentation/home/feed/MyFeedMainActivity.kt
  app/src/main/java/meaning/morning/presentation/home/feed/MyFeedSnsActivity.kt
  app/src/main/java/meaning/morning/presentation/home/feed/PictureRecyclerviewFragment.kt
  app/src/main/java/meaning/morning/presentation/home/feed/SnsRecyclerviewFragment.kt
  app/src/main/res/drawable-hdpi/ellipse_151.png
  app/src/main/res/drawable-mdpi/ellipse_151.png
  app/src/main/res/drawable-xhdpi/ellipse_151.png
  app/src/main/res/drawable-xxhdpi/ellipse_151.png
  app/src/main/res/drawable-xxxhdpi/ellipse_151.png
  app/src/main/res/layout/activity_card_time_stamp.xml
  app/src/main/res/layout/activity_group_feed_sns.xml
  app/src/main/res/layout/activity_my_feed_sns.xml
  app/src/main/res/layout/feed_item_list.xml
  app/src/main/res/layout/sns_item_list.xml
Labels: P 1️⃣, 형준👨‍👧, 🎴Andromeaning
